---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: windows-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Ti

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: windows
  labels:
    app: windows
spec:
  replicas: 1
  strategy:
    type: Recreate

  selector:
    matchLabels:
      app: windows

  template:
    metadata:
      labels:
        app: windows

    spec:
      terminationGracePeriodSeconds: 120

      containers:
        - name: windows
          image: dockurr/windows:latest

          env:
            - name: VERSION
              value: "11"

            # Disco da VM
            - name: DISK_SIZE
              value: "10T"

            # Memória RAM da VM
            - name: RAM_SIZE
              value: "64G"

            # CPUs virtuais
            - name: CPU_CORES
              value: "8"

          ports:
            - containerPort: 8006
              name: http
              protocol: TCP

            - containerPort: 3389
              name: rdp
              protocol: TCP

            - containerPort: 3389
              name: udp
              protocol: UDP

            - containerPort: 5900
              name: vnc
              protocol: TCP

          securityContext:
            privileged: true
            capabilities:
              add:
                - NET_ADMIN

          volumeMounts:
            - name: storage
              mountPath: /storage

            - name: dev-kvm
              mountPath: /dev/kvm

            - name: dev-tun
              mountPath: /dev/net/tun

      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: windows-pvc

        - name: dev-kvm
          hostPath:
            path: /dev/kvm
            type: CharDevice

        - name: dev-tun
          hostPath:
            path: /dev/net/tun
            type: CharDevice

---
apiVersion: v1
kind: Service
metadata:
  name: windows
spec:
  type: ClusterIP

  internalTrafficPolicy: Cluster

  selector:
    app: windows

  ports:
    - name: http
      port: 8006
      targetPort: 8006
      protocol: TCP

    - name: rdp
      port: 3389
      targetPort: 3389
      protocol: TCP

    - name: udp
      port: 3389
      targetPort: 3389
      protocol: UDP

    - name: vnc
      port: 5900
      targetPort: 5900
      protocol: TCP
